### ISSUE TITLE
publish isos with releases

### ISSUE THREAD

**Issue by graingert** [simonvanderveldt/boot2docker-zfs#6]

**Comment by simonvanderveldt** [comment]
@graingert I've updated boot2docker-zfs over the holidays to be up to date with stable Docker. For [1.12.6 ](https://github.com/simonvanderveldt/boot2docker-zfs/releases/tag/v1.12.6-zfs) and going forward I'll make sure to upload the generated ISO. If I have some time to spare I'll setup travis to do it for me :)
